---
title: "Research Log"
author: "Jérémy Genette"
date: "Updated: `r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Research ideas

- According to Hanne, Flemish still perceive phonoloogical voicing difference between g and ch, but the voicing is not to be seen in the phonetic voicing of the fricative

# Devoicing in Belgian French 🇧🇪

Oui, ta présentation s'est très bien passée et les commentaires d'Adèle sont juste à propos de l'environnement. Je pense que les résultats montrent qu'il y a un léger dévoisement en France, mais il est variable. 

A mon avis, on devrait creuser un peu plus, en utilisant ma méthode de détection de voisement + f0 et les intégrer dans le modèle.

Concernant la régression logistique, il faudrait qu'on calcule le VIF pour voir s'il y a une multicolinéarité élevée ou pas. Tu peux regarder ici : 

https://jalalal-tamimi.github.io/R-Stats-Linguistics-Book/8.5-issues-with-glm-and-regression-analyses-in-general.html#checking-collinearity

Mais on devrait regarder un peu plus avec les forêts aléatoires et peut-être gradient boosting machines (que j'ai utilisé pour RFP). 

# RFP - 1-3/07/2026

```{r}
#source("publish.R")
```
